spring:
    application:
        name: address-directory
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
        enabled: true
addressdirectory:
    person:
        page-size: 10